drop TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT (
  SNO      INT          NOT NULL primary key,
  STUNAME  VARCHAR(255) NOT NULL,
  SSEX     CHAR(32)     not null,

  STUAGE   INT          NOT NULL,
  STUGRADE CHAR(32)     NOT NULL
);

DROP TABLE IF EXISTS COURSE;
CREATE TABLE COURSE (

  COURSEID    INT      NOT NULL,
  COURSENAME  CHAR(32) NOT NULL,
  COURSEPRE   CHAR(32) NOT NULL,
  COURSEGRADE INT      NOT NULL,
  PRIMARY KEY (COURSEID)
);

DROP TABLE IF EXISTS SC;
CREATE TABLE SC (
  SNO         INT NOT NULL,
  COURSEID    INT NOT NULL,
  COURSEGRADE INT NOT NULL,
  foreign key (SNO) REFERENCES STUDENT (SNO)
    on DELETE cascade,
  FOREIGN KEY (COURSEID) REFERENCES COURSE (COURSEID)
    on DELETE cascade
);

INSERT INTO STUDENT (SNO, STUNAME, SSEX, STUAGE, STUGRADE) VALUES

  (95001, '李勇', '男', 20, 'CS'),
  (95002, '刘晨', '女', 19, 'ICS'),
  (95003, '王敏', '女', 18, 'MA'),
  (95004, '张立', '男', 19, 'CD');
INSERT INTO COURSE (COURSEID, COURSENAME, COURSEPRE, COURSEGRADE) VALUES

  (1, '数据库', '5', 4),
  (2, '数学	', '', 2),
  (3, '信息系统', '1', 4),
  (4, '操作系统', '6', 3),
  (5, '数据结构', '7', 4),
  (6, '数据处理', '', 2),
  (7, 'PASCAL语言', '6', 4);

INSERT INTO SC (SNO, COURSEID, COURSEGRADE) VALUES
  (95001, 1, 92),
  (95001, 2, 85)
;
